# Support Vector Maschinen

In der heutigen Übung betrachten wir Support Vektor Maschinen.
Dazu werden wir zuerst anhand des Iris-Datensatzes eine Klassifikation durchführen



Erstellen Sie unterschiedliche SVM mit unterschiedlichen Kernenls und berechnen Sie die Erkennungsraten auf dem Iris-Datenset nachdem sie 
die Daten in Train/Test gesplittet haben


In [1]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import confusion_matrix
import sklearn.inspection
import matplotlib.pyplot as plt

import numpy as np

In [2]:
iris = datasets.load_iris()
X = iris.data
y= iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [3]:
svc=SVC(kernel='linear',C=10)
svc.fit(X_train, y_train)

SVC(C=10, kernel='linear')

In [4]:
res = svc.predict(X_test)
confusion_matrix(y_test, res)

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

Visualisieren Sie die Daten anhand https://scikit-learn.org/stable/auto_examples/svm/plot_iris_svc.html


ImportError: cannot import name 'DecisionBoundaryDisplay' from 'sklearn.inspection' (C:\Users\ABleicher\anaconda3\lib\site-packages\sklearn\inspection\__init__.py)

## Eins


Laden Sie einen Datensatz aus https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html herunter und klassifizieren diesen mit SVMs

In [5]:
from sklearn.datasets import load_svmlight_file

data=load_svmlight_file("C://Users//ABleicher//Desktop//csie.ntu.edu.tw_~cjlin_libsvmtools_datasets_binary_a1a.txt") #Doku: https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_svmlight_file.html
X=data[0]
y=data[1]

print(X.shape)
svc=SVC(kernel="linear", C=10)
svc.fit(X,y)

(1605, 119)


SVC(C=10, kernel='linear')

In [6]:
test=load_svmlight_file("C://Users//ABleicher//Desktop//a1a.t")
Xtest=test[0]
ytest=test[1]
res = svc.predict(Xtest[:, :119])
confusion_matrix(ytest, res)

array([[21351,  2159],
       [ 2867,  4579]], dtype=int64)

## Zwei


Verwenden Sie SVM zur Geschlechtsklassifikation anhand gesprochener Sprache.

Die Vorgenesweise ist die folgende:

1. Berechnen von MFCCs mit Hilfe des Paketes python_speech_features
2. Trainieren einer SVM 


Die Daten sind im gitlab-repo zu finden unter gender_data.

Das ist eine Erweiterung der damaligen Geschlechtserkennungs-Aufgabe


Welche Probleme sehen Sie?


In [7]:
import os
import soundfile as sf
import python_speech_features as mfcc


def extract_feats(audiof):
    """extract 20 dim mfcc features from an audio"""
    
    audio,samplerate= sf.read(audiof);
    mfcc_feat = mfcc.mfcc(audio, samplerate, 0.025, 0.01 , 20, appendEnergy=False)

    return mfcc_feat
os.chdir("C:\\Users\\ABleicher\\Desktop\\MachineLearning_SS23-main-6_speechfeatures-notebooks-data\\6_speechfeatures\\notebooks\\data\\LibriSpeech")
def gendermap(utt2spk):
    gender={}
    f=open(utt2spk, 'r')
    for line in f:
        line= ",".join( line.split(" ",1))
        columns=line.split(",")
        gender[columns[0]]=columns[1].strip()
    f.close()
    return gender
trainGenderMap=gendermap('utt2spk.train')
testGenderMap=gendermap('utt2spk.test-10spk')

In [10]:
labels_train=np.empty([0,1])
x_train=np.empty([0,4])

speakers = os.listdir("C:\\Users\\ABleicher\\Desktop\\MachineLearning_SS23-main-6_speechfeatures-notebooks-data\\6_speechfeatures\\notebooks\\data\\LibriSpeech\\train-clean")
for s in speakers:
    sessions=os.listdir("C:\\Users\\ABleicher\\Desktop\\MachineLearning_SS23-main-6_speechfeatures-notebooks-data\\6_speechfeatures\\notebooks\\data\\LibriSpeech\\train-clean\\"+s)
    for session in sessions:
        mfccMatrix = np.empty([0,20])
        files = os.listdir("C:\\Users\\ABleicher\\Desktop\\MachineLearning_SS23-main-6_speechfeatures-notebooks-data\\6_speechfeatures\\notebooks\\data\\LibriSpeech\\train-clean\\"+s+"\\"+session)
        i=1
        for file in files:
            if(os.fsdecode(file).endswith('.flac')):
                mfccMatrix=np.vstack([mfccMatrix, extract_feats("C:\\Users\\ABleicher\\Desktop\\MachineLearning_SS23-main-6_speechfeatures-notebooks-data\\6_speechfeatures\\notebooks\\data\\LibriSpeech\\train-clean\\"+s+"\\"+session+"\\"+file)])
        
        characteristics=np.array([np.mean(mfccMatrix), np.var(mfccMatrix), np.amin(mfccMatrix), np.amax(mfccMatrix)])
        x_train=np.vstack([x_train, characteristics])
        labels_train=np.append(labels_train,trainGenderMap[s])
print("Done")

Done


In [13]:
svc=SVC(kernel="linear", C=10)
svc.fit(x_train,labels_train)

SVC(C=10, kernel='linear')

In [14]:
x_test=np.empty([0,4])
labels_test=np.empty([0,1])

speakers = os.listdir("C:\\Users\\ABleicher\\Desktop\\MachineLearning_SS23-main-6_speechfeatures-notebooks-data\\6_speechfeatures\\notebooks\\data\\LibriSpeech\\test-clean-10spk")
for s in speakers:
    sessions=os.listdir("C:\\Users\\ABleicher\\Desktop\\MachineLearning_SS23-main-6_speechfeatures-notebooks-data\\6_speechfeatures\\notebooks\\data\\LibriSpeech\\test-clean-10spk\\"+s)
    for session in sessions:
        mfccMatrix = np.empty([0,20])
        files = os.listdir("C:\\Users\\ABleicher\\Desktop\\MachineLearning_SS23-main-6_speechfeatures-notebooks-data\\6_speechfeatures\\notebooks\\data\\LibriSpeech\\test-clean-10spk\\"+s+"\\"+session)
        i=1
        for file in files:
            if(os.fsdecode(file).endswith('.flac')):
                mfccMatrix=np.vstack([mfccMatrix, extract_feats("C:\\Users\\ABleicher\\Desktop\\MachineLearning_SS23-main-6_speechfeatures-notebooks-data\\6_speechfeatures\\notebooks\\data\\LibriSpeech\\test-clean-10spk\\"+s+"\\"+session+"\\"+file)])
        
        characteristics=np.array([np.mean(mfccMatrix), np.var(mfccMatrix), np.amin(mfccMatrix), np.amax(mfccMatrix)])
        x_test=np.vstack([x_test, characteristics])
        labels_test=np.append(labels_test,testGenderMap[s])
print("Done")

Done


In [15]:
res = svc.predict(x_test)
confusion_matrix(labels_test, res)

array([[9, 3],
       [3, 5]], dtype=int64)