# Wir implementieren einen Hund-Katze Klassifikator mit neuronalen Netzen

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils
import cv2
from imutils import paths
import numpy as np
import argparse
import os


Done


## Folgende Funktion nimmt ein Bild entgegen, skaliert das Bild auf 32x32 RGB-Pixel, und liefert einen 3072-dim Merkmalevektor zurueck

In [8]:
def image_to_feature_vector(image, size=(32, 32)):
	# resize the image to a fixed size, then flatten the image into
	# a list of raw pixel intensities

    return cv2.resize(image, size).flatten()

## Laden Sie die Daten aus dem gitlab:

- data/train.zip

- data/test100.zip


Schreiben Sie eine Funktion, die die Bilder einliest und mit Hilfe der Funktion image_to_feature_vector vorverarbeiten. Anschließend sollen die Vektoren in eine data-Matrix geschrieben werden. 
Zusätzlich ist ein label-Vektor zu erzeugen. Wie sehen die Labels sinnvollerweise aus?

In [54]:


def getTestData(path):
    Xtrain = np.empty((0,3072))
    ytrain = np.empty([0])
    data = os.listdir(path)
    i=0
    for imgName in data:
        i=i+1
        if((len(data)-i)%1000 ==0):
            print(len(data)-i)
        img = cv2.imread(os.path.join(path,imgName))
        Xtrain = np.append(Xtrain, [image_to_feature_vector(img)], axis=0)
        if("cat" in imgName):
            ytrain=np.append(ytrain, 0) #0=Cat
        else:
            ytrain=np.append(ytrain, 1) #1=Dog
    print("Done")
    return Xtrain, ytrain

Xtrain, ytrain = getTestData("C:\\Users\\ABleicher\\Desktop\\train")

24000
23000
22000
21000
20000
19000
18000
17000
16000
15000
14000
13000
12000
11000
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000
0
Done


In [56]:
print(Xtrain)
print(ytrain)

[[ 93. 171. 210. ...   1.   3.   3.]
 [ 41.  37.  33. ...  31.  36.  51.]
 [ 61.  55.  46. ...   4. 193. 194.]
 ...
 [ 34.  37.  41. ...  98. 133. 163.]
 [246. 245. 250. ... 110. 112. 123.]
 [243. 251. 254. ... 254. 254. 254.]]
[0. 0. 0. ... 1. 1. 1.]


## Splitten Sie die Daten in ein train/test-set.

Macht es Sinn die Daten zu normieren?

In [59]:
(Xtr, Xte, ytr, yte) = train_test_split(Xtrain, ytrain)


(18750, 3072)
(18750,)


# Erstellen Sie ein Neuronales Netz mit Keras

In [62]:
nnet = Sequential()
nnet.add(Dense(64, input_dim=3072, activation='relu'))
#nnet.add(Dense(64, activation='relu'))
#nnet.add(Dense(5, activation='relu'))
nnet.add(Dense(1, activation='sigmoid'))

nnet.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

# ... und starten Sie das Training

In [63]:
nnet.fit(Xtr, ytr, epochs=50, batch_size=100)

Epoch 1/50
188/188 [==============================] - 1s 3ms/step - loss: 419.4304 - accuracy: 0.4997
Epoch 2/50
188/188 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.5011
Epoch 3/50
188/188 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.4985
Epoch 4/50
188/188 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.5011
Epoch 5/50
188/188 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.4997
Epoch 6/50
188/188 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.5011
Epoch 7/50
188/188 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.5011
Epoch 8/50
188/188 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.5011
Epoch 9/50
188/188 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.5011
Epoch 10/50
188/188 [==============================] - 0s 3ms/step - loss: 0.6932 - accuracy: 0.50

# Evaluieren Sie das Netz auf den held-back Test-Daten


Berechnen Sie die Akkuratheit und die Verwechselungsmatrix

In [71]:
import sklearn.metrics as eval

e = nnet.predict(Xte, verbose=0)
res = np.empty((0))
for i in e:
    res = np.append(res, int(i[0]))
print(eval.accuracy_score(yte, res))
print(eval.confusion_matrix(yte, res))

0.5032
[[3145    0]
 [3105    0]]


# Klassifizieren Sie zusätzlich die Daten aus test100 und schauen Sie sich die Ergebnisse an

In [73]:
def getImg(path):
    Xtrain = np.empty((0,3072))
    data = os.listdir(path)
    for imgName in data:
        img = cv2.imread(os.path.join(path,imgName))
        Xtrain = np.append(Xtrain, [image_to_feature_vector(img)], axis=0)
    print("Done")
    return Xtrain

Xtest100 = getImg("C:\\Users\\ABleicher\\Desktop\\test100")

print(nnet.predict(Xtest100))

Done
4/4 [==============================] - 0s 1ms/step
[[0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007577]
 [0.5007

# Verwenden Sie die Merkmalnormierungsmethoden und Testen Sie diese

In [78]:
from tensorflow.keras import regularizers
nnet = Sequential()
nnet.add(Dense(64, kernel_regularizer=regularizers.l2(0.01), input_dim=3072, activation='relu'))
#nnet.add(Dense(64, activation='relu'))
#nnet.add(Dense(5, activation='relu'))
nnet.add(Dense(1, kernel_regularizer=regularizers.l2(0.01), activation='sigmoid'))

nnet.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
nnet.fit(Xtr, ytr, epochs=50, batch_size=100)

Epoch 1/50
188/188 [==============================] - 1s 3ms/step - loss: 10.5625 - accuracy: 0.4972
Epoch 2/50
188/188 [==============================] - 1s 3ms/step - loss: 1.8126 - accuracy: 0.5011
Epoch 3/50
188/188 [==============================] - 0s 3ms/step - loss: 1.7375 - accuracy: 0.5011
Epoch 4/50
188/188 [==============================] - 1s 3ms/step - loss: 1.6733 - accuracy: 0.4943
Epoch 5/50
188/188 [==============================] - 1s 3ms/step - loss: 1.6143 - accuracy: 0.5011
Epoch 6/50
188/188 [==============================] - 1s 3ms/step - loss: 1.5580 - accuracy: 0.4978
Epoch 7/50
188/188 [==============================] - 0s 3ms/step - loss: 1.5036 - accuracy: 0.5011
Epoch 8/50
188/188 [==============================] - 1s 3ms/step - loss: 1.4506 - accuracy: 0.4980
Epoch 9/50
188/188 [==============================] - 1s 3ms/step - loss: 1.4599 - accuracy: 0.5007
Epoch 10/50
188/188 [==============================] - 1s 3ms/step - loss: 1.3678 - accuracy: 0.501